### ISSUE TITLE
incorrect / missing documentation with latest version

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/yamldoc-go#25]
### Proposed Changes 

- publish docs can be fixed by simply removing `push-action` and replacing it with `git push -u origin` (https://github.com/tarunKoyalwar/nucleitest/tree/dev)
- It was observed that latest version of `yamldoc-go` produced less docs/results than earlier versions and removed existing documentation
- This has been visible since `json-templates`PR was merged . adding `json:""` tags somehow caused errors in `yamldoc-go` 
- Investigate and fix this (Note: it seems like errors are skipped/supressed in yamldoc-go, which shouldn't be the case)

**Comment by dogancanbakir** [comment]
@tarunKoyalwar,
https://github.com/tarunKoyalwar/nucleitest returns 404. Could you please update the issue when you have a moment -maybe a bit more context? Thanks!

**Comment by tarunKoyalwar** [comment]
@dogancanbakir , looks like i deleted repo 😄 . i created this issue after looking at https://github.com/projectdiscovery/nuclei/commit/8db0276ba64fabf26e70c87ac715b5870d0b44f8 
we use yamldoc-go to generate syntax-reference . and yamldoc-go has some panic at that point and once it was working after fix it deleted many lines in syntax reference as well as yamldoc-go as you can see in ^ commit . 

not sure if that was a valid change or a bug

**Comment by tarunKoyalwar** [comment]
closing this as it is not reproducible anymore . and syntax reference documentation has less significance now with editor and all other things we have in place
